server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: 'health,info'

springdoc:
  swagger-ui:
    disable-swagger-default-url: 'true'
    path: '/swagger-ui'

spring:
  datasource:
    password: ${database.password}
    driver-class-name: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://postgres-lab-1.neo:5432/arachni
    username: app_tuz
  liquibase:
    enabled: 'false'

objectstorage:
  host: http://arachni-object-storage-devslaves-971395.apps.os-lab-3.neo
  uploadUrl: ${objectstorage.host}/upload
  downloadUrl: ${objectstorage.host}/download