server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: 'health,info'

springdoc:
  swagger-ui:
    disable-swagger-default-url: 'true'
    path: '/swagger-ui'

spring:
  datasource:
    password: ${database.password}
    driver-class-name: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://postgres-lab-1.neo:5432/arachni
    username: app_tuz
  liquibase:
    enabled: 'false'

object-storage:
  host: http://arachni-storage-controller-develop:8080/api
  objectsUrl: ${object-storage.host}/objects